package net.bplaced.clayn.cfs.util;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;
import java.util.function.UnaryOperator;
import java.util.stream.Stream;
import net.bplaced.clayn.cfs.ext.functional.TryingPredicate;
import net.bplaced.clayn.cfs.ext.functional.TryingSupplier;
import net.bplaced.clayn.cfs.ext.functional.TryingUnaryOperator;

/**
 * Utility class for helpful methods for {@link Stream streams}.
 *
 * @author Clayn
 * @since 0.1
 * @version $Revision: 329 $
 */
public final class StreamUtils
{

    /**
     * Generates an stream starting with the {@code first} value and adding the
     * values generated with {@code next} as long as {@code until} returns
     * {@code true} for the current value including {@code first}. {@code until}
     * will also check the first value.
     *
     * @param <T> the type for the values
     * @param first the first value to check and, if accepted, add
     * @param next the operation that generates a new value from the current one
     * @param until the operation that checks the current value and decides if
     * it should be added and the method should continue.
     * @return a stream with all values generated by {@code next} as long as
     * {@code until} returns {@code true}
     * @since 0.1
     */
    public static <T> Stream<T> generateWhile(T first, UnaryOperator<T> next,
            Predicate<T> until)
    {
        List<T> list = new ArrayList<>();
        T val = first;
        while (until.test(val))
        {
            list.add(val);
            val = next.apply(val);
        }
        return list.stream();
    }

    public static <T> Stream<T> generateWhile(TryingSupplier<T> first,
            TryingUnaryOperator<T> next,
            TryingPredicate<T> until)
    {
        Stream.Builder<T> builder = Stream.builder();
        T val = first.get();
        while (until.test(val))
        {
            builder.accept(val);
            val = next.apply(val);
        }
        return builder.build();
    }

    public static <T> Stream<T> generateWhile(TryingSupplier<T> first,
            TryingSupplier<T> next,
            TryingPredicate<T> until)
    {
        return generateWhile(first, (t) -> next.get(), until);
    }

    public static <T> Stream<T> generateWhile(TryingSupplier<T> gen,
            TryingPredicate<T> until)
    {
        return generateWhile(gen, gen, until);
    }
}
